require('dotenv').config();
const mongoose = require('mongoose');
const Employee = require('../../models/Employee');

const employees = [
  {
    name: 'Ahmed Raza',
    email: 'ahmed.raza@example.com',
    phone: '03001234567',
    gender: 'male',
    department: 'Engineering',
    designation: 'Software Engineer',
    salary: 120000,
    joiningDate: '2022-03-15',
  },
  {
    name: 'Ayesha Khan',
    email: 'ayesha.khan@example.com',
    phone: '03011234567',
    gender: 'female',
    department: 'Human Resources',
    designation: 'HR Executive',
    salary: 90000,
    joiningDate: '2021-07-01',
  },
  {
    name: 'Bilal Hussain',
    email: 'bilal.hussain@example.com',
    phone: '03021234567',
    gender: 'male',
    department: 'Sales',
    designation: 'Sales Executive',
    salary: 85000,
    joiningDate: '2023-01-10',
  },
  {
    name: 'Sana Malik',
    email: 'sana.malik@example.com',
    phone: '03031234567',
    gender: 'female',
    department: 'Marketing',
    designation: 'Marketing Manager',
    salary: 150000,
    joiningDate: '2020-11-20',
  },
  {
    name: 'Usman Tariq',
    email: 'usman.tariq@example.com',
    phone: '03041234567',
    gender: 'male',
    department: 'Finance',
    designation: 'Accountant',
    salary: 95000,
    joiningDate: '2022-09-05',
  },
  {
    name: 'Hira Siddiqui',
    email: 'hira.siddiqui@example.com',
    phone: '03051234567',
    gender: 'female',
    department: 'Operations',
    designation: 'Operations Manager',
    salary: 140000,
    joiningDate: '2021-04-12',
  },
  {
    name: 'Fahad Sheikh',
    email: 'fahad.sheikh@example.com',
    phone: '03061234567',
    gender: 'male',
    department: 'Customer Support',
    designation: 'Support Specialist',
    salary: 70000,
    joiningDate: '2023-06-18',
  },
  {
    name: 'Zainab Chaudhry',
    email: 'zainab.chaudhry@example.com',
    phone: '03071234567',
    gender: 'female',
    department: 'IT',
    designation: 'System Administrator',
    salary: 110000,
    joiningDate: '2022-12-01',
  },
  {
    name: 'Imran Qureshi',
    email: 'imran.qureshi@example.com',
    phone: '03081234567',
    gender: 'male',
    department: 'Engineering',
    designation: 'Backend Developer',
    salary: 130000,
    joiningDate: '2021-02-25',
  },
  {
    name: 'Mahnoor Abbasi',
    email: 'mahnoor.abbasi@example.com',
    phone: '03091234567',
    gender: 'female',
    department: 'Sales',
    designation: 'Sales Manager',
    salary: 160000,
    joiningDate: '2020-08-30',
  },
  {
    name: 'Hassan Ali',
    email: 'hassan.ali@example.com',
    phone: '03101234567',
    gender: 'male',
    department: 'IT',
    designation: 'Network Engineer',
    salary: 105000,
    joiningDate: '2022-05-14',
  },
  {
    name: 'Mariam Yousaf',
    email: 'mariam.yousaf@example.com',
    phone: '03111234567',
    gender: 'female',
    department: 'Finance',
    designation: 'Finance Manager',
    salary: 175000,
    joiningDate: '2019-10-22',
  },
  {
    name: 'Adeel Anwar',
    email: 'adeel.anwar@example.com',
    phone: '03121234567',
    gender: 'male',
    department: 'Operations',
    designation: 'Logistics Coordinator',
    salary: 80000,
    joiningDate: '2023-03-08',
  },
  {
    name: 'Sadia Iqbal',
    email: 'sadia.iqbal@example.com',
    phone: '03131234567',
    gender: 'female',
    department: 'Human Resources',
    designation: 'Recruiter',
    salary: 75000,
    joiningDate: '2022-08-19',
  },
  {
    name: 'Kamran Akhtar',
    email: 'kamran.akhtar@example.com',
    phone: '03141234567',
    gender: 'male',
    department: 'Engineering',
    designation: 'QA Engineer',
    salary: 100000,
    joiningDate: '2021-11-30',
  },
  {
    name: 'Rabia Saeed',
    email: 'rabia.saeed@example.com',
    phone: '03151234567',
    gender: 'female',
    department: 'Customer Support',
    designation: 'Support Lead',
    salary: 95000,
    joiningDate: '2020-06-17',
  },
  {
    name: 'Waqas Ahmed',
    email: 'waqas.ahmed@example.com',
    phone: '03161234567',
    gender: 'male',
    department: 'Sales',
    designation: 'Business Development Executive',
    salary: 90000,
    joiningDate: '2023-09-01',
  },
  {
    name: 'Nida Farooq',
    email: 'nida.farooq@example.com',
    phone: '03171234567',
    gender: 'female',
    department: 'Marketing',
    designation: 'Content Strategist',
    salary: 88000,
    joiningDate: '2022-01-25',
  },
  {
    name: 'Junaid Baig',
    email: 'junaid.baig@example.com',
    phone: '03181234567',
    gender: 'male',
    department: 'IT',
    designation: 'IT Support Engineer',
    salary: 72000,
    joiningDate: '2024-02-12',
  },
  {
    name: 'Amna Riaz',
    email: 'amna.riaz@example.com',
    phone: '03191234567',
    gender: 'female',
    department: 'Engineering',
    designation: 'Frontend Developer',
    salary: 115000,
    joiningDate: '2021-06-09',
  },
  {
    name: 'Tariq Mehmood',
    email: 'tariq.mehmood@example.com',
    phone: '03201234567',
    gender: 'male',
    department: 'Finance',
    designation: 'Financial Analyst',
    salary: 98000,
    joiningDate: '2023-04-27',
  },
  {
    name: 'Sobia Nawaz',
    email: 'sobia.nawaz@example.com',
    phone: '03211234567',
    gender: 'female',
    department: 'Operations',
    designation: 'Operations Executive',
    salary: 78000,
    joiningDate: '2022-10-03',
  },
  {
    name: 'Danish Khalid',
    email: 'danish.khalid@example.com',
    phone: '03221234567',
    gender: 'male',
    department: 'Sales',
    designation: 'Regional Sales Manager',
    salary: 170000,
    joiningDate: '2019-12-16',
  },
  {
    name: 'Farah Naseem',
    email: 'farah.naseem@example.com',
    phone: '03231234567',
    gender: 'female',
    department: 'Human Resources',
    designation: 'HR Manager',
    salary: 155000,
    joiningDate: '2020-02-28',
  },
  {
    name: 'Shahzaib Latif',
    email: 'shahzaib.latif@example.com',
    phone: '03241234567',
    gender: 'male',
    department: 'Customer Support',
    designation: 'Customer Success Manager',
    salary: 125000,
    joiningDate: '2021-09-14',
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);

  for (const emp of employees) {
    const exists = await Employee.findOne({ email: emp.email });
    if (exists) {
      console.log(`Skipped (already exists): ${emp.email}`);
      continue;
    }
    await Employee.create(emp);
    console.log(`Created: ${emp.name}`);
  }

  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
